### ISSUE TITLE
assetLoader Service is required in host route and component unit tests

### ISSUE THREAD

**Issue by brandynbennett** [ember-engines/ember-asset-loader#42]
`Attempting to inject an unknown injection: 'service:assetLoader'` is thrown when adding `ember-engines` to project with existing unit tests for routes and components.  Can be worked around by adding `service:assetLoader` to the `needs` array, however this is not ideal and adds unnecessary cognitive load to the addon user.

**Comment by dustinfarris** [comment]
Also getting this, and adding "needs" is not an option in integration tests

**Comment by trentmwillis** [comment]
This issue belongs in [the ember-engines repo](https://github.com/ember-engines/ember-engines/issues), since the issue is a by-product of ember-engines [usage of ember-asset-loader](https://github.com/ember-engines/ember-engines/blob/0742603b052505e288a7c01e71e0f2c3fe8e8aa5/addon/-private/router-ext.js#L18).

Note: I think this should be addressed, but we should track that in the ember-engines repo.

**Comment by trentmwillis** [comment]
Opened https://github.com/ember-engines/ember-engines/issues/294 to replace this.
